services:
    phpbbitalia.topten.listener:
        class: phpbbitalia\toptentopics\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @auth
            - @user
            - @cache
            - @config
            - @content.visibility
            - @dispatcher
            - @pagination
            - @request
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
