services:
    staffit.toptentopics.listener:
        class: staffit\toptentopics\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @template
            - @auth
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @request
        tags:
            - { name: event.listener }
